language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
      
script:
  - mkdir build
  - cd build
  - cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_INSTALL_PYTHON=OFF ..
  - cmake --build . --target install -- -j4
  - export PYTHONPATH=$PYTHONPATH:$PWD/installed/python
  - ctest --output-on-failure
  - cmake -E chdir ../python/MaterialXTest python main.py
